version: '3'

services:
  onlyoffice-documentserver:
    image: onlyoffice/documentserver
    container_name: onlyoffice
    restart: always
    expose:
      - "80"
    networks:
      - onlyoffice

  nginx:
    image: nginx:latest
    container_name: onlyoffice-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - onlyoffice-documentserver
    networks:
      - onlyoffice

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 1; done'"
    networks:
      - onlyoffice

networks:
  onlyoffice:
    driver: bridge
